services:  
  - type: web
    name: elysiajs-hello-world
    runtime: node
    repo: https://github.com/wonglok/bun-socket-template
    plan: free
    envVars:
    - key: BUN_VERSION
      value: 1.1.0
    region: oregon
    buildCommand: bun install
    startCommand: bun start

  - type: pserv
    name: mongodb
    runtime: docker
    dockerfilePath: './DockerfileMongo'
    autoDeploy: true
    disk:
      name: data
      mountPath: /data/db
      sizeGB: 10

version: "1"
